repos:
  - repo: https://github.com/Lucas-C/pre-commit-hooks
    rev: v1.1.9
    hooks:
    - id: remove-crlf
    - id: remove-tabs
  - repo: .
    rev: 3defba6514f1503fcb23585b00b9ef3c48188aa6
    hooks:
    - id: export-requirements-dev
