repos:
  - repo: github.com/Lucas-C/pre-commit-hooks
    sha: v1.1.7
    hooks:
    - id: remove-crlf
    - id: remove-tabs
  - repo: github.com/markdownlint/markdownlint
    rev: master
    hooks:
    - id: markdownlint
