site_name: Bardly
site_author: Sean D Stewart
site_description: The Free & Open-Source Shakespeare Resource.
copyright: "Copyright &copy; 2019 - 2021 Sean Stewart"
site_url: https://bardly.org
repo_url: https://github.com/seandstewart/bardly
repo_name: seandstewart/bardly
docs_dir: bardly
theme:
  favicon: static/img/favicon.ico
  name: "material"
  custom_dir: overrides
  palette:
    primary: "teal"
    accent: "amber"
  font:
    text: "IBM Plex Serif"
    code: "IBM Plex Mono"
  icon:
    logo: flaticon/storytelling-black
  features:
    - tabs
plugins:
  - search:
      prebuild_index: true
  - awesome-pages
  - bardly
markdown_extensions:
  - meta
  - toc:
      permalink: 📃
  - smarty
  - admonition
  - footnotes
  - pymdownx.details
  - pymdownx.magiclink
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
      options:
        custom_icons:
          - overrides/.icons
  - pymdownx.tabbed
  - attr_list
extra:
  social:
    - icon: "fontawesome/brands/github-alt"
      link: "https://github.com/seandstewart/bardly"
    - icon: "fontawesome/brands/twitter"
      link: "https://twitter.com/MrSeanStewart"
    - icon: "fontawesome/brands/linkedin"
      link: "https://linkedin.com/in/seandstewart"
    - icon: "flaticon/logo"
      link: "https://www.flaticon.com"
      name: Icons made by Freepik on Flaticon
extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/tablesort/5.2.1/tablesort.min.js
  - https://cdnjs.cloudflare.com/ajax/libs/tablesort/5.2.1/sorts/tablesort.number.min.js
  - static/javascripts/tablesort.js
extra_css:
  - static/stylesheets/extra.css
