site_name: Bardly
site_author: Sean D Stewart
copyright: "Copyright &copy; 2019 - 2020 Sean Stewart"
site_url: https://bardly.org
repo_url: https://github.com/seandstewart/bardly
repo_name: seandstewart/bardly
docs_dir: bardly
theme:
  favicon: static/img/favicon.ico
  name: "material"
  custom_dir: overrides
  palette:
    primary: "teal"
    accent: "amber"
  font:
    text: "IBM Plex Serif"
    code: "IBM Plex Mono"
  icon:
    logo: fontawesome/solid/hat-wizard
  features:
    - tabs
plugins:
  - search
  - awesome-pages
  - bardly
markdown_extensions:
  - toc:
      permalink: 📃
  - smarty
  - admonition
  - footnotes
  - pymdownx.details
  - pymdownx.magiclink
  - pymdownx.tabbed
  - attr_list
extra:
  social:
    - icon: "fontawesome/brands/github-alt"
      link: "https://github.com/seandstewart/bardly"
    - icon: "fontawesome/brands/twitter"
      link: "https://twitter.com/MrSeanStewart"
    - icon: "fontawesome/brands/linkedin"
      link: "https://linkedin.com/in/seandstewart"
extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/tablesort/5.2.1/tablesort.min.js
  - static/javascripts/tables.js
extra_css:
  - static/stylesheets/extra.css
