site_name: Bardly
site_author: Sean D Stewart
copyright: "Copyright &copy; 2019 - 2020 Sean Stewart"
site_url: https://bardly.com
repo_url: https://github.com/seandstewart/bardly
repo_name: seandstewart/bardly
docs_dir: bardly
theme:
  favicon: static/img/favicon.ico
  name: "material"
  palette:
    primary: "teal"
    accent: "amber"
  font:
    text: "IBM Plex Serif"
    code: "IBM Plex Mono"
  icon:
    logo: fontawesome/solid/hat-wizard
  features:
    - tabs
plugins:
  - search
  - awesome-pages
  - bardly
markdown_extensions:
  - toc:
      permalink: "#"
  - smarty
  - admonition
  - footnotes
  - codehilite
  - pymdownx.arithmatex
  - pymdownx.inlinehilite
  - pymdownx.superfences
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - attr_list
extra:
  social:
    - icon: "fontawesome/brands/github-alt"
      link: "https://github.com/seandstewart/bardly"
    - icon: "fontawesome/brands/twitter"
      link: "https://twitter.com/MrSeanStewart"
    - icon: "fontawesome/brands/linkedin"
      link: "https://linkedin.com/in/seandstewart"
#  manifest: "img/img/site.webmanifest"
